pipeline{
    agent any


    tools{
        jdk 'JDK11'
        maven 'Maven'
    }

    stages{
        stage('Git Checkout'){
            steps{
                git branch: 'main', url: 'https://github.com/Showrya18/test-1.git'
            }
        }
        stage('Compile'){
            steps{
                sh 'mvn compile'
            }
        }
        stage('Build'){
            steps{
                sh 'mvn clean install'
            }
        }
        stage('Build Docker Image'){
            steps{
                sh 'docker build -t showrya18/project:1 -f webapp/Dockerfile webapp'
            }
        }
        stage('Docker image scan'){
            steps{
                sh 'trivy image --format table -o trvy-image-report.html showrya18/project:1'
            }
        }
        stage('Containersation'){
            steps{
                sh 'docker run -it -d --name c1 -p 9000:8080 showrya18/project:1'
            }
        }
        stage('Login to Docker Hub'){
            steps{
                script{
                    withCredentials([usernamePassword(credentialsID: 'dockerhub-credentials', passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USERNAME')]){
                        sh 'echo $DOCKER_PASSWORD | docker login -u $USERNAME --password-stdin'
                    }
                }
            }
        }
        stage('Push Docker Image to Docker Hub'){
            steps{
                sh 'docker push Showrya18/project:1'
            }
        }
    }

}